import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, writeFile, rename, unlink } from "node:fs/promises";
import path from "node:path";
import { usageRequests } from "./requests.js";
import { callEventSchema, reportInputSchema, usageEventSchema, sanitizeValue, redactText, type UsageEvent, type ReportInput, type ReportEvent, type CallEvent } from "./events.js";

export interface UsageStoreOptions { retentionDays?: number; now?: () => Date }
/** One atomic file per event avoids lost updates between concurrent calls/processes. No network sink. */
export class UsageStore {
  readonly retentionDays: number;
  private readonly now: () => Date;
  private flagQueue: Promise<void> = Promise.resolve();
  constructor(readonly directory: string, options: UsageStoreOptions = {}) {
    this.retentionDays = options.retentionDays ?? 7;
    if (!Number.isFinite(this.retentionDays) || this.retentionDays <= 0) throw new Error("retentionDays must be positive");
    this.now = options.now ?? (() => new Date());
  }
  private isLive(at: string): boolean {
    const age = this.now().getTime() - Date.parse(at);
    return age >= -60_000 && age < this.retentionDays * 86_400_000;
  }
  async appendCall(event: CallEvent): Promise<void> {
    const valid = callEventSchema.parse(event);
    valid.args = sanitizeValue(valid.args) as Record<string, unknown>;
    valid.server = redactText(valid.server);
    valid.tool = redactText(valid.tool);
    if (Object.hasOwn(valid, "result")) valid.result = sanitizeValue(valid.result);
    if (valid.request) {
      valid.request.text = redactText(valid.request.text);
      if (valid.request.intent) valid.request.intent = redactText(valid.request.intent);
    }
    if (valid.error) valid.error.message = redactText(valid.error.message);
    await this.write(valid);
  }
  private async write(event: UsageEvent): Promise<void> {
    const valid = usageEventSchema.parse(event);
    if (!this.isLive(valid.at)) throw new Error("Event is expired or dated in the future");
    await mkdir(this.directory, { recursive: true, mode: 0o700 });
    const temporary = path.join(this.directory, `${valid.id}.${randomUUID()}.tmp`);
    try {
      await writeFile(temporary, JSON.stringify(valid) + "\n", { mode: 0o600, flag: "wx" });
      // IDs generated by the SDK; refuse duplicates instead of overwriting evidence.
      const { link } = await import("node:fs/promises");
      await link(temporary, path.join(this.directory, `${valid.id}.json`));
    } finally { await unlink(temporary).catch(() => undefined); }
  }
  async read(): Promise<UsageEvent[]> {
    const events: UsageEvent[] = [];
    let names: string[];
    try { names = await readdir(this.directory); } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
      throw error;
    }
    for (const name of names.filter(name => /^[a-f0-9-]{36}\.json$/.test(name)).sort()) {
      const event = usageEventSchema.parse(JSON.parse(await readFile(path.join(this.directory, name), "utf8")) as unknown);
      if (name !== `${event.id}.json`) throw new Error("Event filename and ID disagree");
      if (this.isLive(event.at)) events.push(event);
    }
    return events.sort((a, b) => a.at.localeCompare(b.at) || a.id.localeCompare(b.id));
  }
  /** Import only the selected, user-reviewed excerpt; never fetch a transcript or share link. */
  async report(input: ReportInput, redactions: readonly string[] = []): Promise<ReportEvent> {
    const parsed = reportInputSchema.parse(input);
    if (Date.parse(parsed.consent.reviewedAt) > this.now().getTime() + 60_000) throw new Error("Review date is in the future");
    const calls = new Set((await this.read()).filter(event => event.kind === "call").map(event => event.id));
    if (parsed.callIds.some(id => !calls.has(id))) throw new Error("Report references an unknown or expired call");
    const event = usageEventSchema.parse({ ...parsed, version: 1, kind: "report", id: randomUUID(), at: this.now().toISOString(),
      asked: sanitizeValue(parsed.asked, redactions), expected: sanitizeValue(parsed.expected, redactions), got: sanitizeValue(parsed.got, redactions),
      excerpt: parsed.excerpt.map(turn => ({ ...turn, text: sanitizeValue(turn.text, redactions) })),
    }) as ReportEvent;
    await this.write(event);
    return event;
  }
  /** One explicit human action; context comes from the retained call group shown by the host UI. */
  async flag(callId: string, consent: ReportInput["consent"]): Promise<ReportEvent> {
    const pending = this.flagQueue.then(() => this.recordFlag(callId, consent));
    this.flagQueue = pending.then(() => undefined, () => undefined);
    return pending;
  }
  private async recordFlag(callId: string, consent: ReportInput["consent"]): Promise<ReportEvent> {
    reportInputSchema.shape.consent.parse(consent);
    const request = usageRequests(await this.read()).find(r => r.calls.some(c => c.id === callId));
    if (!request) throw new Error("Unknown or expired call");
    const duplicate = request.reports.find(r => r.flag);
    if (duplicate) return duplicate;
    return this.report({
      callIds: request.calls.map(c => c.id), asked: request.asked, provenance: request.provenance,
      expected: "User flagged: this was not what I wanted; desired behavior has not been supplied",
      got: request.calls.map(c => `${c.tool}: ${c.error?.message ?? (Object.hasOwn(c, "result") ? JSON.stringify(c.result) : "Result payload was not captured")}`).join("\n").slice(0, 12000),
      outcome: "failure", flag: true, consent, excerpt: [],
    });
  }
  /** Physically remove expired records. Read/analytics already exclude them. Schedule this in the host. */
  async prune(): Promise<number> {
    let names: string[];
    try { names = await readdir(this.directory); } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return 0;
      throw error;
    }
    let removed = 0;
    for (const name of names.filter(name => /^[a-f0-9-]{36}\.json$/.test(name))) {
      const file = path.join(this.directory, name);
      const event = usageEventSchema.parse(JSON.parse(await readFile(file, "utf8")) as unknown);
      if (!this.isLive(event.at)) { await unlink(file); removed++; }
    }
    return removed;
  }
}
export async function writeUsageOutput(file: string, value: unknown): Promise<void> {
  await mkdir(path.dirname(file), { recursive: true, mode: 0o700 });
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, JSON.stringify(value, null, 2) + "\n", { mode: 0o600, flag: "wx" });
    await rename(temporary, file);
  } finally { await unlink(temporary).catch(() => undefined); }
}
