#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const projectRoot = path.resolve(process.env.INIT_CWD || process.cwd());
const isSelfInstall = projectRoot === packageRoot || projectRoot.startsWith(`${packageRoot}${path.sep}`);
const disabled = process.env.MCP_OBSERVATORY_POSTINSTALL === "0" ||
  process.env.MCP_OBSERVATORY_DISABLE_POSTINSTALL === "1";
const forceAuto = process.env.MCP_OBSERVATORY_AUTO_SETUP_CI === "1";
const isCi = process.env.CI === "true" || process.env.GITHUB_ACTIONS === "true";

function readJson(filePath) {
  try {
    return JSON.parse(readFileSync(filePath, "utf8"));
  } catch {
    return undefined;
  }
}

function hasOwn(value, key) {
  return Object.prototype.hasOwnProperty.call(value || {}, key);
}

function isLikelyMcpProject(pkg) {
  const keywords = Array.isArray(pkg?.keywords) ? pkg.keywords.map(String) : [];
  const deps = { ...(pkg?.dependencies || {}), ...(pkg?.devDependencies || {}), ...(pkg?.peerDependencies || {}) };
  return Boolean(pkg?.mcpName) ||
    keywords.some((keyword) => /^(mcp|mcp-server|model-context-protocol)$/i.test(keyword)) ||
    hasOwn(deps, "@modelcontextprotocol/sdk") ||
    Object.keys(pkg?.scripts || {}).some((name) => /(^|:)mcp($|:|-)/i.test(name));
}

function inferCommand(pkg, config) {
  if (process.env.MCP_OBSERVATORY_TARGET_COMMAND) return process.env.MCP_OBSERVATORY_TARGET_COMMAND;
  if (typeof config?.command === "string" && config.command.trim()) return config.command.trim();
  const scripts = pkg?.scripts || {};
  for (const name of ["mcp", "start:mcp", "server:mcp", "mcp:serve", "dev:mcp"]) {
    if (typeof scripts[name] === "string") return `npm run ${name}`;
  }
  if (typeof pkg?.name === "string" && pkg.name.trim()) return `npx -y ${pkg.name}`;
  return "npx -y <server-package>";
}

function yamlString(value) {
  return JSON.stringify(value);
}

function yamlFor(command, sarif) {
  return [
    "name: MCP Observatory",
    "",
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "",
    "permissions:",
    "  contents: read",
    ...(sarif ? ["  security-events: write"] : []),
    "",
    "jobs:",
    "  mcp-observatory:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v6",
    "      - uses: KryptosAI/mcp-observatory/action@v0.27.0",
    "        with:",
    `          command: ${yamlString(command)}`,
    "          deep: true",
    "          security: true",
    "          comment-on-pr: false",
    "          set-status: false",
    ...(sarif ? ["          upload-sarif: true"] : []),
    "          # Generated by @kryptosai/mcp-observatory postinstall.",
    "",
  ].join("\n");
}

function writeCi(projectRoot, command, sarif) {
  const workflowPath = path.join(projectRoot, ".github", "workflows", "mcp-observatory.yml");
  mkdirSync(path.dirname(workflowPath), { recursive: true });
  try {
    writeFileSync(workflowPath, yamlFor(command, sarif), { encoding: "utf8", flag: "wx" });
    return { status: "created", workflowPath };
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "EEXIST") {
      return { status: "exists", workflowPath };
    }
    throw error;
  }
}

function log(message) {
  process.stderr.write(`${message}\n`);
}

try {
  if (disabled || isSelfInstall || isCi) process.exit(0);

  const pkg = readJson(path.join(projectRoot, "package.json"));
  if (!pkg || !isLikelyMcpProject(pkg)) process.exit(0);

  const config = pkg.mcpObservatory && typeof pkg.mcpObservatory === "object" ? pkg.mcpObservatory : {};
  const command = inferCommand(pkg, config);
  const sarif = config.sarif === true || process.env.MCP_OBSERVATORY_AUTO_SETUP_SARIF === "1";
  const autoSetup = forceAuto || config.autoSetupCi === true;

  if (autoSetup) {
    const result = writeCi(projectRoot, command, sarif);
    const relative = path.relative(projectRoot, result.workflowPath);
    log(result.status === "created"
      ? `MCP Observatory: created ${relative}. Verify with: npx @kryptosai/mcp-observatory setup-ci --doctor`
      : `MCP Observatory: ${relative} already exists. Verify with: npx @kryptosai/mcp-observatory setup-ci --doctor`);
  } else {
    log(`MCP Observatory: CI ready. Run: npx @kryptosai/mcp-observatory setup-ci --all --command "${command.replaceAll("\"", "\\\"")}"${sarif ? " --sarif" : ""}`);
    log("MCP Observatory: to auto-create CI on install, set package.json mcpObservatory.autoSetupCi=true.");
  }
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  log(`MCP Observatory: install-time CI helper skipped (${message}).`);
}
